import { keyframes } from '@emotion/core';
import { css } from '@emotion/core';

/* ----------------------------------------------
 * The following animations were generated by Animista
 * w: http://animista.net, t: @cssanimista
 *
 * jello-horizontal
 * ----------------------------------------
 */

const jelloHorizontalKeyframe = keyframes`
  0% {
    transform: scale3d(1, 1, 1);
  }

  30% {
    transform: scale3d(1.25, 0.75, 1);
  }

  40% {
    transform: scale3d(0.75, 1.25, 1);
  }

  50% {
    transform: scale3d(1.15, 0.85, 1);
  }

  65% {
    transform: scale3d(0.95, 1.05, 1);
  }

  75% {
    transform: scale3d(1.05, 0.95, 1);
  }

  100% {
    transform: scale3d(1, 1, 1);
  }
`;

const jelloHorizontalOnHover = css`
  &:hover {
    animation: ${jelloHorizontalKeyframe} 0.9s both;
  }
`;

export default jelloHorizontalOnHover;
