[build.environment]
  NODE_VERSION = "15.11.0"
  NPM_VERSION = "7.6.0"

[build]
  publish = "public"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[[plugins]]
  package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  baseUrl = "https://www.wittenbrockdesign.com"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"

	[plugins.inputs]

	# The base url of your site (optional, default = main URL set in Netlify)
	baseUrl = "https://www.wittenbrockdesign.com"

	# Path to the sitemap URL (optional, default = /sitemap.xml)
	sitemapPath = "/sitemap.xml"

	providers = [
		"google",
		"bing",
		"yandex"
	]