[[headers]]
  for = "/*"
  [headers.value]
    X-Frame-Options: DENY
    X-XSS-Protection: 1; mode=block
    Referrer-Policy: strict-origin-when-cross-origin
    X-Content-Type-Options: nosniff
    Feature-Policy = "camera 'none'; geolocation 'none'; microphone 'none'"
    Content-Security-Policy = '''
      script-src 'self' https://www.googletagmanager.com https://www.google-analytics.com;
      style-src 'self';
      img-src 'self' https://res.cloudinary.com;
      connect-src 'self'
      font-src 'self';
      object-src 'none';
      media-src 'self';
      frame-src 'self';
      child-src 'self';
      form-action 'self';
      frame-ancestors 'none';'''
  
  [build.environment]
    NODE_VERSION = "15.0.1"
    NPM_VERSION = "7.0.15"